steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/bjir-artifact/data-vis:$COMMIT_SHA'
    - '.'
  - name: gcr.io/cloud-builders/docker
    args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/bjir-artifact/data-vis:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'model-vis'
    - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/bjir-artifact/data-vis:$COMMIT_SHA'
    - '--region=us-central1'
    - '--cpu=1'
    - '--memory=2048Mi'
    - '--allow-unauthenticated'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/bjir-artifact/data-vis:$COMMIT_SHA'
logsBucket: 'gs://bjir-bucket/logs'